### ISSUE TITLE
Code block actually tries to run code

### ISSUE THREAD

**Issue by jordyvandomselaar** [FormidableLabs/spectacle-boilerplate-mdx#16]
I have the following piece of markdown:

![image](https://user-images.githubusercontent.com/12712484/59965890-681b1280-9514-11e9-9651-84ef9a49a232.png)

It's a screenshot because github tries to render it as a code block…

---

I get the following error in my slides:

```
ERROR in ./presentation/reducers.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: ENOENT: no such file or directory, open '/Users/jordyvandomselaar/workspace/redux-meetup/presentation/reducers.js'
```

It actually tries to import the file? I just want it to display the code.

**Comment by jordyvandomselaar** [comment]
It suddenly started working. No idea what happened, just a heads up.

**Comment by TrevorBurnham** [comment]
I'm seeing this same bug. It's really weird:

```js
import foo from 'foo';
```

works as expected, but

```js
import foo from 'foo';
import bar from 'bar';
```

errors with

```
ERROR in ./presentation/index.mdx
Module not found: Error: Can't resolve 'bar'
```

If I flip the lines around, it's `foo` that can't be resolved. So it seems like the first `import` in a code block is (correctly) ignored as presentation content, but any subsequent `import`s are executed.
