### ISSUE TITLE
runtime error viewing build

### ISSUE THREAD

**Issue by shedali** [FormidableLabs/spectacle-boilerplate-mdx#7]
`npm install` ✓

`npm run build` ✓

`npx serve -s . `

```
bundle.js:6 Uncaught TypeError: u.default.map is not a function
```

`npm run deploy` --> http://selfish-friends.surge.sh/#/

node v11.0.0
npm 6.4.1

**Comment by willklein** [comment]
Getting the same with Yarn `1.12.3`, Node `9.10.1` and NPM `5.6.0`. Tested in a fresh `git clone` of the repo with no changes.

Happy to help investigate, as I need to deploy a slide deck for CascadiaJS next week.

**Comment by NicholasBoll** [comment]
I traced the failure back to this line: https://github.com/FormidableLabs/spectacle-boilerplate-mdx/blob/master/index.js#L31

It seems the `webpack.config.production.js` doesn't handle mdx. MDX support was added in this commit on this line: https://github.com/FormidableLabs/spectacle-boilerplate-mdx/commit/0be4cf9020916622f721d0b03bfc1e363b95926f#diff-11e9f7f953edc64ba14b0cc350ae7b9dR30

I'll submit a PR to handle MDX the same in production as it does in development.
